apiVersion: v1
kind: Service
metadata: 
  name: burp-service
spec: 
  selector: 
    app: burpee-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
